import { StyleSheet } from "react-native";

export const settingsUiStyles = StyleSheet.create({
  pageHeader: {
    gap: 6,
  },
  heading: {
    color: "#111827",
    fontSize: 28,
    fontWeight: "800",
    marginTop: 8,
  },
  subheading: {
    color: "#4B5563",
    fontSize: 14,
    lineHeight: 20,
  },
  scrollContent: {
    gap: 16,
    paddingBottom: 24,
  },
  backButton: {
    alignSelf: "flex-start",
    borderColor: "#D1D5DB",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  backButtonLabel: {
    color: "#0F172A",
    fontSize: 13,
    fontWeight: "700",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderColor: "#D8DEE9",
    borderRadius: 14,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  cardTitle: {
    color: "#0F172A",
    fontSize: 16,
    fontWeight: "700",
  },
  loadingRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  settingLabel: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "700",
  },
  optionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  optionChip: {
    borderColor: "#CBD5E1",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  optionChipActive: {
    backgroundColor: "#E0EAFF",
    borderColor: "#4F7DF3",
  },
  optionChipLabel: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "600",
  },
  optionChipLabelActive: {
    color: "#1D4ED8",
  },
  settingRow: {
    alignItems: "center",
    borderColor: "#CBD5E1",
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  settingTextWrap: {
    flex: 1,
    gap: 2,
  },
  settingTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "700",
  },
  settingHint: {
    color: "#64748B",
    fontSize: 12,
    lineHeight: 18,
  },
  settingValue: {
    color: "#1D4ED8",
    fontSize: 13,
    fontWeight: "700",
    minWidth: 32,
    textAlign: "right",
  },
  sectionDivider: {
    backgroundColor: "#E2E8F0",
    height: 1,
    marginVertical: 2,
  },
  textInput: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    borderRadius: 10,
    borderWidth: 1,
    color: "#111827",
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  textAreaInput: {
    minHeight: 84,
  },
  inputDisabled: {
    opacity: 0.65,
  },
  metaText: {
    color: "#334155",
    fontSize: 14,
    lineHeight: 20,
  },
  errorText: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "600",
  },
  successText: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "600",
  },
  inlineInfoBox: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    borderRadius: 12,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  inlineInfoTitle: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#111827",
    borderRadius: 10,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: 12,
  },
  primaryButtonLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  secondaryButton: {
    alignItems: "center",
    borderColor: "#D1D5DB",
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 12,
  },
  secondaryButtonLabel: {
    color: "#0F172A",
    fontSize: 14,
    fontWeight: "700",
  },
  dangerButton: {
    alignItems: "center",
    borderColor: "#FECACA",
    borderRadius: 10,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 12,
  },
  dangerButtonLabel: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonPressed: {
    opacity: 0.85,
  },
  supportMessageList: {
    maxHeight: 360,
    minHeight: 220,
  },
  supportMessageListContent: {
    gap: 10,
    paddingBottom: 4,
  },
  supportStatusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  supportSummaryRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "space-between",
  },
  supportStatusChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  supportStatusChipOpen: {
    backgroundColor: "#DCFCE7",
    borderColor: "#86EFAC",
  },
  supportStatusChipInfo: {
    backgroundColor: "#DBEAFE",
    borderColor: "#93C5FD",
  },
  supportStatusChipWarn: {
    backgroundColor: "#FEF3C7",
    borderColor: "#FCD34D",
  },
  supportStatusChipMuted: {
    backgroundColor: "#E2E8F0",
    borderColor: "#CBD5E1",
  },
  supportStatusChipLabel: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  supportStatusChipLabelOpen: {
    color: "#166534",
  },
  supportStatusChipLabelInfo: {
    color: "#1D4ED8",
  },
  supportStatusChipLabelWarn: {
    color: "#B45309",
  },
  supportStatusChipLabelMuted: {
    color: "#475569",
  },
  supportConversationPanel: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  supportConversationHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  supportConversationTitle: {
    color: "#0F172A",
    fontSize: 15,
    fontWeight: "800",
  },
  supportConversationMeta: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "700",
  },
  supportActionButton: {
    flex: 1,
    minWidth: 140,
  },
  supportPresetGroup: {
    gap: 10,
  },
  supportPresetHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  supportEmptyState: {
    backgroundColor: "#FFFFFF",
    borderColor: "#D8DEE9",
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  supportMessageBubble: {
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  supportMessageBubbleUser: {
    alignSelf: "flex-end",
    backgroundColor: "#E0EAFF",
    borderColor: "#BFDBFE",
    maxWidth: "92%",
  },
  supportMessageBubbleAdmin: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFFFF",
    borderColor: "#D8DEE9",
    maxWidth: "92%",
  },
  supportMessageAuthor: {
    color: "#0F172A",
    fontSize: 12,
    fontWeight: "800",
  },
  supportMessageBody: {
    color: "#1F2937",
    fontSize: 14,
    lineHeight: 20,
  },
  supportMessageTime: {
    color: "#64748B",
    fontSize: 11,
    fontWeight: "600",
  },
  supportComposerCard: {
    backgroundColor: "#FFFFFF",
    borderColor: "#D8DEE9",
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  supportComposerTitle: {
    color: "#0F172A",
    fontSize: 14,
    fontWeight: "800",
  },
  supportComposerInput: {
    backgroundColor: "#FFFFFF",
    minHeight: 112,
    textAlignVertical: "top",
  },
  subscriptionSummaryCard: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  subscriptionSummaryCardApproved: {
    backgroundColor: "#ECFDF5",
    borderColor: "#6EE7B7",
  },
  subscriptionApprovalBanner: {
    alignSelf: "flex-start",
    backgroundColor: "#10B981",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  subscriptionApprovalBannerLabel: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
  },
  subscriptionRequestCard: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  subscriptionHistoryCard: {
    backgroundColor: "#F8FAFC",
    borderColor: "#E2E8F0",
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  subscriptionEmptyState: {
    gap: 10,
  },
  subscriptionHeaderRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  subscriptionTitleWrap: {
    flex: 1,
    gap: 2,
  },
  subscriptionPlanName: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
  },
  subscriptionStatusPill: {
    borderRadius: 999,
    fontSize: 11,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
    textTransform: "uppercase",
  },
  subscriptionStatusPillFree: {
    backgroundColor: "#E2E8F0",
    color: "#475569",
  },
  subscriptionStatusPillPro: {
    backgroundColor: "#DBEAFE",
    color: "#1D4ED8",
  },
  subscriptionStatusPillPremium: {
    backgroundColor: "#DCFCE7",
    color: "#047857",
  },
  subscriptionRequestStatus: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  subscriptionJourneySteps: {
    gap: 10,
  },
  subscriptionJourneyStep: {
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 12,
  },
  subscriptionJourneyStepDone: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  subscriptionJourneyStepCurrent: {
    backgroundColor: "#EFF6FF",
    borderColor: "#93C5FD",
  },
  subscriptionJourneyStepUpcoming: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
  },
  subscriptionJourneyStepNumber: {
    borderRadius: 999,
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  subscriptionJourneyStepNumberDone: {
    backgroundColor: "#10B981",
    color: "#FFFFFF",
  },
  subscriptionJourneyStepNumberCurrent: {
    backgroundColor: "#2563EB",
    color: "#FFFFFF",
  },
  subscriptionJourneyStepNumberUpcoming: {
    backgroundColor: "#E2E8F0",
    color: "#475569",
  },
  subscriptionJourneyStepTextWrap: {
    flex: 1,
    gap: 2,
  },
  subscriptionActionButton: {
    flex: 1,
    minWidth: 140,
  },
  planCatalogCard: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    borderRadius: 12,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  planCatalogCardActive: {
    backgroundColor: "#EFF6FF",
    borderColor: "#93C5FD",
  },
  planFeatureList: {
    gap: 4,
  },
  planFeatureText: {
    color: "#334155",
    fontSize: 13,
  },
  proofUploadCard: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    borderRadius: 12,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  proofPreviewImage: {
    backgroundColor: "#E2E8F0",
    borderRadius: 12,
    height: 180,
    width: "100%",
  },
  proofPreviewPressable: {
    gap: 8,
  },
  proofPreviewCaptionRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  proofPreviewCaption: {
    color: "#64748B",
    fontSize: 12,
    fontWeight: "600",
  },
  proofPreviewCaptionAction: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "700",
  },
  proofActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  proofFullscreenBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.82)",
    flex: 1,
    justifyContent: "center",
    padding: 18,
  },
  proofFullscreenOverlay: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  proofFullscreenCard: {
    backgroundColor: "#0F172A",
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: 20,
    borderWidth: 1,
    gap: 14,
    maxHeight: "86%",
    padding: 16,
    width: "100%",
  },
  proofFullscreenHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  proofFullscreenTitle: {
    color: "#F8FAFC",
    flex: 1,
    fontSize: 16,
    fontWeight: "800",
  },
  proofFullscreenImage: {
    backgroundColor: "#020617",
    borderRadius: 16,
    height: 520,
    maxHeight: "100%",
    width: "100%",
  },
  sessionCard: {
    backgroundColor: "#F8FAFC",
    borderColor: "#CBD5E1",
    borderRadius: 10,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  sessionCardHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sessionDeviceLabel: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "700",
    maxWidth: "72%",
  },
  sessionBucket: {
    color: "#334155",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  sessionMeta: {
    color: "#475569",
    fontSize: 12,
  },
  summaryBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#E0EAFF",
    borderRadius: 999,
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
});
