import { StyleSheet } from "react-native";

export const settingsUiStyles = StyleSheet.create({
  pageHeader: {
    gap: 8,
  },
  pageHeaderCard: {
    backgroundColor: "#FFFDF8",
    borderColor: "#D8D4C9",
    borderRadius: 20,
    borderWidth: 1,
    padding: 16,
  },
  pageHeaderTopRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  heading: {
    color: "#202321",
    fontSize: 30,
    fontWeight: "800",
    marginTop: 4,
  },
  subheading: {
    color: "#6E706B",
    fontSize: 14,
    lineHeight: 21,
  },
  scrollContent: {
    gap: 18,
    paddingBottom: 24,
  },
  backButton: {
    alignSelf: "flex-start",
    backgroundColor: "#F8F5EE",
    borderColor: "#D8D4C9",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  backButtonLabel: {
    color: "#D76F55",
    fontSize: 13,
    fontWeight: "800",
  },
  card: {
    backgroundColor: "#FFFDF8",
    borderColor: "#D8D4C9",
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 16,
  },
  cardTitle: {
    color: "#202321",
    fontSize: 17,
    fontWeight: "800",
  },
  loadingRow: {
    alignItems: "center",
    backgroundColor: "#F8F5EE",
    borderColor: "#E3DED3",
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  settingLabel: {
    color: "#6E706B",
    fontSize: 12,
    fontWeight: "700",
  },
  optionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  optionChip: {
    backgroundColor: "#F8F5EE",
    borderColor: "#D8D4C9",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  optionChipActive: {
    backgroundColor: "#E7EFE9",
    borderColor: "#A8C9BD",
  },
  optionChipLabel: {
    color: "#4F514B",
    fontSize: 12,
    fontWeight: "700",
  },
  optionChipLabelActive: {
    color: "#48766B",
  },
  settingRow: {
    alignItems: "center",
    backgroundColor: "#F8F5EE",
    borderColor: "#D8D4C9",
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  settingTextWrap: {
    flex: 1,
    gap: 3,
  },
  settingTitle: {
    color: "#202321",
    fontSize: 15,
    fontWeight: "800",
  },
  settingHint: {
    color: "#6E706B",
    fontSize: 12,
    lineHeight: 18,
  },
  settingValue: {
    color: "#48766B",
    fontSize: 13,
    fontWeight: "700",
    minWidth: 32,
    textAlign: "right",
  },
  sectionDivider: {
    backgroundColor: "#E3DED3",
    height: 1,
    marginVertical: 4,
  },
  textInput: {
    backgroundColor: "#F8F5EE",
    borderColor: "#D8D4C9",
    borderRadius: 14,
    borderWidth: 1,
    color: "#202321",
    fontSize: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  textAreaInput: {
    minHeight: 96,
  },
  inputDisabled: {
    opacity: 0.65,
  },
  metaText: {
    color: "#4F514B",
    fontSize: 14,
    lineHeight: 20,
  },
  errorText: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "600",
  },
  successText: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "600",
  },
  inlineInfoBox: {
    backgroundColor: "#F8F5EE",
    borderColor: "#D8D4C9",
    borderRadius: 16,
    borderWidth: 1,
    gap: 5,
    padding: 12,
  },
  inlineInfoTitle: {
    color: "#48766B",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  primaryButton: {
    alignItems: "center",
    backgroundColor: "#D76F55",
    borderRadius: 14,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: 14,
  },
  primaryButtonLabel: {
    color: "#FFFDF8",
    fontSize: 14,
    fontWeight: "800",
  },
  secondaryButton: {
    alignItems: "center",
    backgroundColor: "#FFFDF8",
    borderColor: "#D8D4C9",
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 46,
    paddingHorizontal: 14,
  },
  secondaryButtonLabel: {
    color: "#202321",
    fontSize: 14,
    fontWeight: "800",
  },
  dangerButton: {
    alignItems: "center",
    backgroundColor: "#FFF5F5",
    borderColor: "#FECACA",
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 46,
    paddingHorizontal: 14,
  },
  dangerButtonLabel: {
    color: "#B91C1C",
    fontSize: 13,
    fontWeight: "800",
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonPressed: {
    opacity: 0.85,
  },
  supportMessageList: {
    maxHeight: 360,
    minHeight: 220,
  },
  supportMessageListContent: {
    gap: 10,
    paddingBottom: 4,
  },
  supportStatusRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  supportSummaryRow: {
    alignItems: "center",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "space-between",
  },
  supportStatusChip: {
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  supportStatusChipOpen: {
    backgroundColor: "#DCFCE7",
    borderColor: "#86EFAC",
  },
  supportStatusChipInfo: {
    backgroundColor: "#DBEAFE",
    borderColor: "#93C5FD",
  },
  supportStatusChipWarn: {
    backgroundColor: "#FEF3C7",
    borderColor: "#FCD34D",
  },
  supportStatusChipMuted: {
    backgroundColor: "#E3DED3",
    borderColor: "#CFC9BD",
  },
  supportStatusChipLabel: {
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  supportStatusChipLabelOpen: {
    color: "#166534",
  },
  supportStatusChipLabelInfo: {
    color: "#48766B",
  },
  supportStatusChipLabelWarn: {
    color: "#B45309",
  },
  supportStatusChipLabelMuted: {
    color: "#6E706B",
  },
  supportConversationPanel: {
    backgroundColor: "#F8F5EE",
    borderColor: "#CFC9BD",
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    padding: 12,
  },
  supportConversationHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  supportConversationTitle: {
    color: "#202321",
    fontSize: 15,
    fontWeight: "800",
  },
  supportConversationMeta: {
    color: "#6E706B",
    fontSize: 12,
    fontWeight: "700",
  },
  supportActionButton: {
    flex: 1,
    minWidth: 140,
  },
  supportPresetGroup: {
    gap: 10,
  },
  supportPresetHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  supportEmptyState: {
    backgroundColor: "#FFFDF8",
    borderColor: "#D8D4C9",
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  supportMessageBubble: {
    borderRadius: 14,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  supportMessageBubbleUser: {
    alignSelf: "flex-end",
    backgroundColor: "#E0EAFF",
    borderColor: "#BFDBFE",
    maxWidth: "92%",
  },
  supportMessageBubbleAdmin: {
    alignSelf: "flex-start",
    backgroundColor: "#FFFDF8",
    borderColor: "#D8D4C9",
    maxWidth: "92%",
  },
  supportMessageAuthor: {
    color: "#202321",
    fontSize: 12,
    fontWeight: "800",
  },
  supportMessageBody: {
    color: "#1F2937",
    fontSize: 14,
    lineHeight: 20,
  },
  supportMessageTime: {
    color: "#6E706B",
    fontSize: 11,
    fontWeight: "600",
  },
  supportComposerCard: {
    backgroundColor: "#FFFDF8",
    borderColor: "#D8D4C9",
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  supportComposerTitle: {
    color: "#202321",
    fontSize: 14,
    fontWeight: "800",
  },
  supportComposerInput: {
    backgroundColor: "#FFFDF8",
    minHeight: 112,
    textAlignVertical: "top",
  },
  subscriptionSummaryCard: {
    backgroundColor: "#F8F5EE",
    borderColor: "#CFC9BD",
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  subscriptionFeatureList: {
    gap: 10,
  },
  subscriptionFeatureRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 9,
  },
  subscriptionFeatureBullet: {
    color: "#4F46E5",
    fontSize: 15,
    fontWeight: "900",
  },
  subscriptionFeatureText: {
    color: "#4F514B",
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
  },
  subscriptionSummaryCardApproved: {
    backgroundColor: "#ECFDF5",
    borderColor: "#6EE7B7",
  },
  subscriptionApprovalBanner: {
    alignSelf: "flex-start",
    backgroundColor: "#10B981",
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  subscriptionApprovalBannerLabel: {
    color: "#FFFDF8",
    fontSize: 12,
    fontWeight: "800",
  },
  subscriptionRequestCard: {
    backgroundColor: "#F8F5EE",
    borderColor: "#CFC9BD",
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  subscriptionHistoryCard: {
    backgroundColor: "#F8F5EE",
    borderColor: "#E3DED3",
    borderRadius: 12,
    borderWidth: 1,
    gap: 6,
    padding: 12,
  },
  subscriptionEmptyState: {
    gap: 10,
  },
  subscriptionHeaderRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  subscriptionTitleWrap: {
    flex: 1,
    gap: 2,
  },
  subscriptionPlanName: {
    color: "#202321",
    fontSize: 15,
    fontWeight: "800",
  },
  subscriptionStatusPill: {
    borderRadius: 999,
    fontSize: 11,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 3,
    textTransform: "uppercase",
  },
  subscriptionStatusPillFree: {
    backgroundColor: "#E3DED3",
    color: "#6E706B",
  },
  subscriptionStatusPillPro: {
    backgroundColor: "#DBEAFE",
    color: "#48766B",
  },
  subscriptionStatusPillPremium: {
    backgroundColor: "#DCFCE7",
    color: "#047857",
  },
  subscriptionRequestStatus: {
    color: "#48766B",
    fontSize: 12,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  subscriptionJourneySteps: {
    gap: 10,
  },
  subscriptionJourneyStep: {
    alignItems: "center",
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: "row",
    gap: 10,
    padding: 12,
  },
  subscriptionJourneyStepDone: {
    backgroundColor: "#ECFDF5",
    borderColor: "#A7F3D0",
  },
  subscriptionJourneyStepCurrent: {
    backgroundColor: "#EFF6FF",
    borderColor: "#93C5FD",
  },
  subscriptionJourneyStepUpcoming: {
    backgroundColor: "#F8F5EE",
    borderColor: "#CFC9BD",
  },
  subscriptionJourneyStepNumber: {
    borderRadius: 999,
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  subscriptionJourneyStepNumberDone: {
    backgroundColor: "#10B981",
    color: "#FFFDF8",
  },
  subscriptionJourneyStepNumberCurrent: {
    backgroundColor: "#D76F55",
    color: "#FFFDF8",
  },
  subscriptionJourneyStepNumberUpcoming: {
    backgroundColor: "#E3DED3",
    color: "#6E706B",
  },
  subscriptionJourneyStepTextWrap: {
    flex: 1,
    gap: 2,
  },
  subscriptionActionButton: {
    flex: 1,
    minWidth: 140,
  },
  planCatalogCard: {
    backgroundColor: "#F8F5EE",
    borderColor: "#CFC9BD",
    borderRadius: 12,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  planCatalogCardActive: {
    backgroundColor: "#EFF6FF",
    borderColor: "#93C5FD",
  },
  planFeatureList: {
    gap: 4,
  },
  planFeatureText: {
    color: "#4F514B",
    fontSize: 13,
  },
  proofUploadCard: {
    backgroundColor: "#F8F5EE",
    borderColor: "#CFC9BD",
    borderRadius: 12,
    borderWidth: 1,
    gap: 10,
    padding: 12,
  },
  proofPreviewImage: {
    backgroundColor: "#E3DED3",
    borderRadius: 12,
    height: 180,
    width: "100%",
  },
  proofPreviewPressable: {
    gap: 8,
  },
  proofPreviewCaptionRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  proofPreviewCaption: {
    color: "#6E706B",
    fontSize: 12,
    fontWeight: "600",
  },
  proofPreviewCaptionAction: {
    color: "#48766B",
    fontSize: 12,
    fontWeight: "700",
  },
  proofActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  proofFullscreenBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.82)",
    flex: 1,
    justifyContent: "center",
    padding: 18,
  },
  proofFullscreenOverlay: {
    bottom: 0,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  proofFullscreenCard: {
    backgroundColor: "#202321",
    borderColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: 20,
    borderWidth: 1,
    gap: 14,
    maxHeight: "86%",
    padding: 16,
    width: "100%",
  },
  proofFullscreenHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  proofFullscreenTitle: {
    color: "#F8F5EE",
    flex: 1,
    fontSize: 16,
    fontWeight: "800",
  },
  proofFullscreenImage: {
    backgroundColor: "#020617",
    borderRadius: 16,
    height: 520,
    maxHeight: "100%",
    width: "100%",
  },
  sessionCard: {
    backgroundColor: "#F8F5EE",
    borderColor: "#CFC9BD",
    borderRadius: 10,
    borderWidth: 1,
    gap: 4,
    padding: 10,
  },
  sessionCardHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sessionDeviceLabel: {
    color: "#202321",
    fontSize: 13,
    fontWeight: "700",
    maxWidth: "72%",
  },
  sessionBucket: {
    color: "#4F514B",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  sessionMeta: {
    color: "#6E706B",
    fontSize: 12,
  },
  summaryBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#E0EAFF",
    borderRadius: 999,
    color: "#48766B",
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  homeSummaryCard: {
    backgroundColor: "#FFFDF8",
    borderColor: "#D8D4C9",
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  homeSummaryHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
  },
  homeSummaryTextWrap: {
    flex: 1,
    gap: 4,
  },
  homeSummaryName: {
    color: "#202321",
    fontSize: 21,
    fontWeight: "800",
    lineHeight: 27,
  },
  homeSummaryEmail: {
    color: "#6E706B",
    fontSize: 13,
    lineHeight: 18,
  },
  homeSummaryPlanPill: {
    alignSelf: "flex-start",
    backgroundColor: "#ECFDF5",
    borderRadius: 999,
    color: "#047857",
    fontSize: 12,
    fontWeight: "800",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  homeSummaryMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  homeSummaryMetaChip: {
    backgroundColor: "#F8F5EE",
    borderColor: "#E3DED3",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  homeSummaryMetaLabel: {
    color: "#6E706B",
    fontSize: 12,
    fontWeight: "700",
  },
  homeStatusList: {
    gap: 6,
  },
  homeSummaryStatusText: {
    color: "#B91C1C",
    fontSize: 12,
    lineHeight: 18,
  },
  homeSectionCard: {
    gap: 14,
    padding: 16,
  },
  homeSectionHeader: {
    gap: 4,
  },
  homeSectionTitle: {
    color: "#202321",
    fontSize: 18,
    fontWeight: "800",
  },
  homeSectionHint: {
    color: "#6E706B",
    fontSize: 13,
    lineHeight: 19,
  },
  homeLinkList: {
    gap: 10,
  },
  homeLinkRow: {
    alignItems: "center",
    backgroundColor: "#F8F5EE",
    borderColor: "#E3DED3",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  homeLinkBadge: {
    alignItems: "center",
    borderRadius: 12,
    justifyContent: "center",
    minHeight: 46,
    minWidth: 54,
    paddingHorizontal: 8,
  },
  homeLinkBadgeLabel: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  homeLinkTextWrap: {
    flex: 1,
    gap: 3,
  },
  homeLinkTitle: {
    color: "#202321",
    fontSize: 15,
    fontWeight: "800",
  },
  homeLinkHint: {
    color: "#6E706B",
    fontSize: 12,
    lineHeight: 18,
  },
  homeLinkMetaWrap: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: 8,
    justifyContent: "flex-end",
    minWidth: 68,
  },
  homeLinkValue: {
    color: "#D76F55",
    fontSize: 13,
    fontWeight: "800",
    maxWidth: 80,
    textAlign: "right",
  },
  homeLinkChevron: {
    color: "#94A3B8",
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 18,
  },
  homeToneBadgeAmber: {
    backgroundColor: "#FEF3C7",
  },
  homeToneBadgeBlue: {
    backgroundColor: "#DBEAFE",
  },
  homeToneBadgeGreen: {
    backgroundColor: "#DCFCE7",
  },
  homeToneBadgePurple: {
    backgroundColor: "#F3E8FF",
  },
  homeToneBadgeSlate: {
    backgroundColor: "#E3DED3",
  },
  homeToneBadgeLabelAmber: {
    color: "#B45309",
  },
  homeToneBadgeLabelBlue: {
    color: "#48766B",
  },
  homeToneBadgeLabelGreen: {
    color: "#15803D",
  },
  homeToneBadgeLabelPurple: {
    color: "#7C3AED",
  },
  homeToneBadgeLabelSlate: {
    color: "#6E706B",
  },
  homeToneCardAmber: {
    backgroundColor: "#FFF7ED",
    borderColor: "#FED7AA",
  },
  homeToneCardBlue: {
    backgroundColor: "#EFF6FF",
    borderColor: "#BFDBFE",
  },
  homeToneCardGreen: {
    backgroundColor: "#F0FDF4",
    borderColor: "#BBF7D0",
  },
  homeToneCardPurple: {
    backgroundColor: "#FAF5FF",
    borderColor: "#E9D5FF",
  },
  homeToneCardSlate: {
    backgroundColor: "#F8F5EE",
    borderColor: "#CFC9BD",
  },
});
