/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppSupportRouteImport } from './routes/_app/support'
import { Route as AppSubscriptionRouteImport } from './routes/_app/subscription'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppQuestionPapersRouteImport } from './routes/_app/question-papers'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppPracticeRouteImport } from './routes/_app/practice'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppQuestionPapersIndexRouteImport } from './routes/_app/question-papers/index'
import { Route as AppPracticeIndexRouteImport } from './routes/_app/practice/index'
import { Route as AppQuestionPapersNewRouteImport } from './routes/_app/question-papers/new'
import { Route as AppQuestionPapersPaperIdRouteImport } from './routes/_app/question-papers/$paperId'
import { Route as AppPracticeSessionIdRouteImport } from './routes/_app/practice/$sessionId'
import { Route as AppQuestionPapersPaperIdManageRouteImport } from './routes/_app/question-papers/$paperId.manage'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionRoute = AppSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionPapersRoute = AppQuestionPapersRouteImport.update({
  id: '/question-papers',
  path: '/question-papers',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeRoute = AppPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionPapersIndexRoute = AppQuestionPapersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppQuestionPapersRoute,
} as any)
const AppPracticeIndexRoute = AppPracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPracticeRoute,
} as any)
const AppQuestionPapersNewRoute = AppQuestionPapersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppQuestionPapersRoute,
} as any)
const AppQuestionPapersPaperIdRoute =
  AppQuestionPapersPaperIdRouteImport.update({
    id: '/$paperId',
    path: '/$paperId',
    getParentRoute: () => AppQuestionPapersRoute,
  } as any)
const AppPracticeSessionIdRoute = AppPracticeSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AppPracticeRoute,
} as any)
const AppQuestionPapersPaperIdManageRoute =
  AppQuestionPapersPaperIdManageRouteImport.update({
    id: '/manage',
    path: '/manage',
    getParentRoute: () => AppQuestionPapersPaperIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/practice': typeof AppPracticeRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/question-papers': typeof AppQuestionPapersRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/support': typeof AppSupportRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/practice/$sessionId': typeof AppPracticeSessionIdRoute
  '/question-papers/$paperId': typeof AppQuestionPapersPaperIdRouteWithChildren
  '/question-papers/new': typeof AppQuestionPapersNewRoute
  '/practice/': typeof AppPracticeIndexRoute
  '/question-papers/': typeof AppQuestionPapersIndexRoute
  '/question-papers/$paperId/manage': typeof AppQuestionPapersPaperIdManageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/settings': typeof AppSettingsRoute
  '/subscription': typeof AppSubscriptionRoute
  '/support': typeof AppSupportRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/practice/$sessionId': typeof AppPracticeSessionIdRoute
  '/question-papers/$paperId': typeof AppQuestionPapersPaperIdRouteWithChildren
  '/question-papers/new': typeof AppQuestionPapersNewRoute
  '/practice': typeof AppPracticeIndexRoute
  '/question-papers': typeof AppQuestionPapersIndexRoute
  '/question-papers/$paperId/manage': typeof AppQuestionPapersPaperIdManageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/practice': typeof AppPracticeRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/question-papers': typeof AppQuestionPapersRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/subscription': typeof AppSubscriptionRoute
  '/_app/support': typeof AppSupportRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/practice/$sessionId': typeof AppPracticeSessionIdRoute
  '/_app/question-papers/$paperId': typeof AppQuestionPapersPaperIdRouteWithChildren
  '/_app/question-papers/new': typeof AppQuestionPapersNewRoute
  '/_app/practice/': typeof AppPracticeIndexRoute
  '/_app/question-papers/': typeof AppQuestionPapersIndexRoute
  '/_app/question-papers/$paperId/manage': typeof AppQuestionPapersPaperIdManageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/practice'
    | '/profile'
    | '/question-papers'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/practice/$sessionId'
    | '/question-papers/$paperId'
    | '/question-papers/new'
    | '/practice/'
    | '/question-papers/'
    | '/question-papers/$paperId/manage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/subscription'
    | '/support'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/practice/$sessionId'
    | '/question-papers/$paperId'
    | '/question-papers/new'
    | '/practice'
    | '/question-papers'
    | '/question-papers/$paperId/manage'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/practice'
    | '/_app/profile'
    | '/_app/question-papers'
    | '/_app/settings'
    | '/_app/subscription'
    | '/_app/support'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_app/practice/$sessionId'
    | '/_app/question-papers/$paperId'
    | '/_app/question-papers/new'
    | '/_app/practice/'
    | '/_app/question-papers/'
    | '/_app/question-papers/$paperId/manage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subscription': {
      id: '/_app/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AppSubscriptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/question-papers': {
      id: '/_app/question-papers'
      path: '/question-papers'
      fullPath: '/question-papers'
      preLoaderRoute: typeof AppQuestionPapersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice': {
      id: '/_app/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AppPracticeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/question-papers/': {
      id: '/_app/question-papers/'
      path: '/'
      fullPath: '/question-papers/'
      preLoaderRoute: typeof AppQuestionPapersIndexRouteImport
      parentRoute: typeof AppQuestionPapersRoute
    }
    '/_app/practice/': {
      id: '/_app/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof AppPracticeIndexRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/question-papers/new': {
      id: '/_app/question-papers/new'
      path: '/new'
      fullPath: '/question-papers/new'
      preLoaderRoute: typeof AppQuestionPapersNewRouteImport
      parentRoute: typeof AppQuestionPapersRoute
    }
    '/_app/question-papers/$paperId': {
      id: '/_app/question-papers/$paperId'
      path: '/$paperId'
      fullPath: '/question-papers/$paperId'
      preLoaderRoute: typeof AppQuestionPapersPaperIdRouteImport
      parentRoute: typeof AppQuestionPapersRoute
    }
    '/_app/practice/$sessionId': {
      id: '/_app/practice/$sessionId'
      path: '/$sessionId'
      fullPath: '/practice/$sessionId'
      preLoaderRoute: typeof AppPracticeSessionIdRouteImport
      parentRoute: typeof AppPracticeRoute
    }
    '/_app/question-papers/$paperId/manage': {
      id: '/_app/question-papers/$paperId/manage'
      path: '/manage'
      fullPath: '/question-papers/$paperId/manage'
      preLoaderRoute: typeof AppQuestionPapersPaperIdManageRouteImport
      parentRoute: typeof AppQuestionPapersPaperIdRoute
    }
  }
}

interface AppPracticeRouteChildren {
  AppPracticeSessionIdRoute: typeof AppPracticeSessionIdRoute
  AppPracticeIndexRoute: typeof AppPracticeIndexRoute
}

const AppPracticeRouteChildren: AppPracticeRouteChildren = {
  AppPracticeSessionIdRoute: AppPracticeSessionIdRoute,
  AppPracticeIndexRoute: AppPracticeIndexRoute,
}

const AppPracticeRouteWithChildren = AppPracticeRoute._addFileChildren(
  AppPracticeRouteChildren,
)

interface AppQuestionPapersPaperIdRouteChildren {
  AppQuestionPapersPaperIdManageRoute: typeof AppQuestionPapersPaperIdManageRoute
}

const AppQuestionPapersPaperIdRouteChildren: AppQuestionPapersPaperIdRouteChildren =
  {
    AppQuestionPapersPaperIdManageRoute: AppQuestionPapersPaperIdManageRoute,
  }

const AppQuestionPapersPaperIdRouteWithChildren =
  AppQuestionPapersPaperIdRoute._addFileChildren(
    AppQuestionPapersPaperIdRouteChildren,
  )

interface AppQuestionPapersRouteChildren {
  AppQuestionPapersPaperIdRoute: typeof AppQuestionPapersPaperIdRouteWithChildren
  AppQuestionPapersNewRoute: typeof AppQuestionPapersNewRoute
  AppQuestionPapersIndexRoute: typeof AppQuestionPapersIndexRoute
}

const AppQuestionPapersRouteChildren: AppQuestionPapersRouteChildren = {
  AppQuestionPapersPaperIdRoute: AppQuestionPapersPaperIdRouteWithChildren,
  AppQuestionPapersNewRoute: AppQuestionPapersNewRoute,
  AppQuestionPapersIndexRoute: AppQuestionPapersIndexRoute,
}

const AppQuestionPapersRouteWithChildren =
  AppQuestionPapersRoute._addFileChildren(AppQuestionPapersRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppPracticeRoute: typeof AppPracticeRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppQuestionPapersRoute: typeof AppQuestionPapersRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppSubscriptionRoute: typeof AppSubscriptionRoute
  AppSupportRoute: typeof AppSupportRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppPracticeRoute: AppPracticeRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppQuestionPapersRoute: AppQuestionPapersRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppSubscriptionRoute: AppSubscriptionRoute,
  AppSupportRoute: AppSupportRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
