/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedUsersRouteImport } from './routes/_protected/users'
import { Route as ProtectedTaxonomyRouteImport } from './routes/_protected/taxonomy'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedQuestionsRouteImport } from './routes/_protected/questions'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedQuestionsIndexRouteImport } from './routes/_protected/questions/index'
import { Route as ProtectedUsersSupportRouteImport } from './routes/_protected/users/support'
import { Route as ProtectedUsersSubscriptionsRouteImport } from './routes/_protected/users/subscriptions'
import { Route as ProtectedTaxonomySubjectsRouteImport } from './routes/_protected/taxonomy/subjects'
import { Route as ProtectedTaxonomySubChaptersRouteImport } from './routes/_protected/taxonomy/sub-chapters'
import { Route as ProtectedTaxonomyGradesRouteImport } from './routes/_protected/taxonomy/grades'
import { Route as ProtectedTaxonomyChaptersRouteImport } from './routes/_protected/taxonomy/chapters'
import { Route as ProtectedSettingsSecurityRouteImport } from './routes/_protected/settings/security'
import { Route as ProtectedSettingsProfileRouteImport } from './routes/_protected/settings/profile'
import { Route as ProtectedQuestionsNewRouteImport } from './routes/_protected/questions/new'
import { Route as ProtectedQuestionsImportRouteImport } from './routes/_protected/questions/import'
import { Route as ProtectedQuestionsBlueprintsRouteImport } from './routes/_protected/questions/blueprints'
import { Route as ProtectedQuestionsBlueprintsIndexRouteImport } from './routes/_protected/questions/blueprints/index'
import { Route as ProtectedQuestionsQuestionIdIndexRouteImport } from './routes/_protected/questions/$questionId/index'
import { Route as ProtectedQuestionsBlueprintsNewRouteImport } from './routes/_protected/questions/blueprints/new'
import { Route as ProtectedQuestionsQuestionIdEditRouteImport } from './routes/_protected/questions/$questionId/edit'
import { Route as ProtectedQuestionsBlueprintsBlueprintIdEditRouteImport } from './routes/_protected/questions/blueprints/$blueprintId/edit'

const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTaxonomyRoute = ProtectedTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedQuestionsRoute = ProtectedQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedUsersRoute,
} as any)
const ProtectedQuestionsIndexRoute = ProtectedQuestionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedQuestionsRoute,
} as any)
const ProtectedUsersSupportRoute = ProtectedUsersSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ProtectedUsersRoute,
} as any)
const ProtectedUsersSubscriptionsRoute =
  ProtectedUsersSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => ProtectedUsersRoute,
  } as any)
const ProtectedTaxonomySubjectsRoute =
  ProtectedTaxonomySubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => ProtectedTaxonomyRoute,
  } as any)
const ProtectedTaxonomySubChaptersRoute =
  ProtectedTaxonomySubChaptersRouteImport.update({
    id: '/sub-chapters',
    path: '/sub-chapters',
    getParentRoute: () => ProtectedTaxonomyRoute,
  } as any)
const ProtectedTaxonomyGradesRoute = ProtectedTaxonomyGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => ProtectedTaxonomyRoute,
} as any)
const ProtectedTaxonomyChaptersRoute =
  ProtectedTaxonomyChaptersRouteImport.update({
    id: '/chapters',
    path: '/chapters',
    getParentRoute: () => ProtectedTaxonomyRoute,
  } as any)
const ProtectedSettingsSecurityRoute =
  ProtectedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedSettingsProfileRoute =
  ProtectedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => ProtectedSettingsRoute,
  } as any)
const ProtectedQuestionsNewRoute = ProtectedQuestionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedQuestionsRoute,
} as any)
const ProtectedQuestionsImportRoute =
  ProtectedQuestionsImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => ProtectedQuestionsRoute,
  } as any)
const ProtectedQuestionsBlueprintsRoute =
  ProtectedQuestionsBlueprintsRouteImport.update({
    id: '/blueprints',
    path: '/blueprints',
    getParentRoute: () => ProtectedQuestionsRoute,
  } as any)
const ProtectedQuestionsBlueprintsIndexRoute =
  ProtectedQuestionsBlueprintsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedQuestionsBlueprintsRoute,
  } as any)
const ProtectedQuestionsQuestionIdIndexRoute =
  ProtectedQuestionsQuestionIdIndexRouteImport.update({
    id: '/$questionId/',
    path: '/$questionId/',
    getParentRoute: () => ProtectedQuestionsRoute,
  } as any)
const ProtectedQuestionsBlueprintsNewRoute =
  ProtectedQuestionsBlueprintsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedQuestionsBlueprintsRoute,
  } as any)
const ProtectedQuestionsQuestionIdEditRoute =
  ProtectedQuestionsQuestionIdEditRouteImport.update({
    id: '/$questionId/edit',
    path: '/$questionId/edit',
    getParentRoute: () => ProtectedQuestionsRoute,
  } as any)
const ProtectedQuestionsBlueprintsBlueprintIdEditRoute =
  ProtectedQuestionsBlueprintsBlueprintIdEditRouteImport.update({
    id: '/$blueprintId/edit',
    path: '/$blueprintId/edit',
    getParentRoute: () => ProtectedQuestionsBlueprintsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/questions': typeof ProtectedQuestionsRouteWithChildren
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/taxonomy': typeof ProtectedTaxonomyRouteWithChildren
  '/users': typeof ProtectedUsersRouteWithChildren
  '/questions/blueprints': typeof ProtectedQuestionsBlueprintsRouteWithChildren
  '/questions/import': typeof ProtectedQuestionsImportRoute
  '/questions/new': typeof ProtectedQuestionsNewRoute
  '/settings/profile': typeof ProtectedSettingsProfileRoute
  '/settings/security': typeof ProtectedSettingsSecurityRoute
  '/taxonomy/chapters': typeof ProtectedTaxonomyChaptersRoute
  '/taxonomy/grades': typeof ProtectedTaxonomyGradesRoute
  '/taxonomy/sub-chapters': typeof ProtectedTaxonomySubChaptersRoute
  '/taxonomy/subjects': typeof ProtectedTaxonomySubjectsRoute
  '/users/subscriptions': typeof ProtectedUsersSubscriptionsRoute
  '/users/support': typeof ProtectedUsersSupportRoute
  '/questions/': typeof ProtectedQuestionsIndexRoute
  '/users/': typeof ProtectedUsersIndexRoute
  '/questions/$questionId/edit': typeof ProtectedQuestionsQuestionIdEditRoute
  '/questions/blueprints/new': typeof ProtectedQuestionsBlueprintsNewRoute
  '/questions/$questionId/': typeof ProtectedQuestionsQuestionIdIndexRoute
  '/questions/blueprints/': typeof ProtectedQuestionsBlueprintsIndexRoute
  '/questions/blueprints/$blueprintId/edit': typeof ProtectedQuestionsBlueprintsBlueprintIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forbidden': typeof ForbiddenRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRouteWithChildren
  '/taxonomy': typeof ProtectedTaxonomyRouteWithChildren
  '/questions/import': typeof ProtectedQuestionsImportRoute
  '/questions/new': typeof ProtectedQuestionsNewRoute
  '/settings/profile': typeof ProtectedSettingsProfileRoute
  '/settings/security': typeof ProtectedSettingsSecurityRoute
  '/taxonomy/chapters': typeof ProtectedTaxonomyChaptersRoute
  '/taxonomy/grades': typeof ProtectedTaxonomyGradesRoute
  '/taxonomy/sub-chapters': typeof ProtectedTaxonomySubChaptersRoute
  '/taxonomy/subjects': typeof ProtectedTaxonomySubjectsRoute
  '/users/subscriptions': typeof ProtectedUsersSubscriptionsRoute
  '/users/support': typeof ProtectedUsersSupportRoute
  '/questions': typeof ProtectedQuestionsIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/questions/$questionId/edit': typeof ProtectedQuestionsQuestionIdEditRoute
  '/questions/blueprints/new': typeof ProtectedQuestionsBlueprintsNewRoute
  '/questions/$questionId': typeof ProtectedQuestionsQuestionIdIndexRoute
  '/questions/blueprints': typeof ProtectedQuestionsBlueprintsIndexRoute
  '/questions/blueprints/$blueprintId/edit': typeof ProtectedQuestionsBlueprintsBlueprintIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/questions': typeof ProtectedQuestionsRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsRouteWithChildren
  '/_protected/taxonomy': typeof ProtectedTaxonomyRouteWithChildren
  '/_protected/users': typeof ProtectedUsersRouteWithChildren
  '/_protected/questions/blueprints': typeof ProtectedQuestionsBlueprintsRouteWithChildren
  '/_protected/questions/import': typeof ProtectedQuestionsImportRoute
  '/_protected/questions/new': typeof ProtectedQuestionsNewRoute
  '/_protected/settings/profile': typeof ProtectedSettingsProfileRoute
  '/_protected/settings/security': typeof ProtectedSettingsSecurityRoute
  '/_protected/taxonomy/chapters': typeof ProtectedTaxonomyChaptersRoute
  '/_protected/taxonomy/grades': typeof ProtectedTaxonomyGradesRoute
  '/_protected/taxonomy/sub-chapters': typeof ProtectedTaxonomySubChaptersRoute
  '/_protected/taxonomy/subjects': typeof ProtectedTaxonomySubjectsRoute
  '/_protected/users/subscriptions': typeof ProtectedUsersSubscriptionsRoute
  '/_protected/users/support': typeof ProtectedUsersSupportRoute
  '/_protected/questions/': typeof ProtectedQuestionsIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
  '/_protected/questions/$questionId/edit': typeof ProtectedQuestionsQuestionIdEditRoute
  '/_protected/questions/blueprints/new': typeof ProtectedQuestionsBlueprintsNewRoute
  '/_protected/questions/$questionId/': typeof ProtectedQuestionsQuestionIdIndexRoute
  '/_protected/questions/blueprints/': typeof ProtectedQuestionsBlueprintsIndexRoute
  '/_protected/questions/blueprints/$blueprintId/edit': typeof ProtectedQuestionsBlueprintsBlueprintIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forbidden'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/questions'
    | '/settings'
    | '/taxonomy'
    | '/users'
    | '/questions/blueprints'
    | '/questions/import'
    | '/questions/new'
    | '/settings/profile'
    | '/settings/security'
    | '/taxonomy/chapters'
    | '/taxonomy/grades'
    | '/taxonomy/sub-chapters'
    | '/taxonomy/subjects'
    | '/users/subscriptions'
    | '/users/support'
    | '/questions/'
    | '/users/'
    | '/questions/$questionId/edit'
    | '/questions/blueprints/new'
    | '/questions/$questionId/'
    | '/questions/blueprints/'
    | '/questions/blueprints/$blueprintId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forbidden'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/settings'
    | '/taxonomy'
    | '/questions/import'
    | '/questions/new'
    | '/settings/profile'
    | '/settings/security'
    | '/taxonomy/chapters'
    | '/taxonomy/grades'
    | '/taxonomy/sub-chapters'
    | '/taxonomy/subjects'
    | '/users/subscriptions'
    | '/users/support'
    | '/questions'
    | '/users'
    | '/questions/$questionId/edit'
    | '/questions/blueprints/new'
    | '/questions/$questionId'
    | '/questions/blueprints'
    | '/questions/blueprints/$blueprintId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/forbidden'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_protected/dashboard'
    | '/_protected/questions'
    | '/_protected/settings'
    | '/_protected/taxonomy'
    | '/_protected/users'
    | '/_protected/questions/blueprints'
    | '/_protected/questions/import'
    | '/_protected/questions/new'
    | '/_protected/settings/profile'
    | '/_protected/settings/security'
    | '/_protected/taxonomy/chapters'
    | '/_protected/taxonomy/grades'
    | '/_protected/taxonomy/sub-chapters'
    | '/_protected/taxonomy/subjects'
    | '/_protected/users/subscriptions'
    | '/_protected/users/support'
    | '/_protected/questions/'
    | '/_protected/users/'
    | '/_protected/questions/$questionId/edit'
    | '/_protected/questions/blueprints/new'
    | '/_protected/questions/$questionId/'
    | '/_protected/questions/blueprints/'
    | '/_protected/questions/blueprints/$blueprintId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/users': {
      id: '/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/taxonomy': {
      id: '/_protected/taxonomy'
      path: '/taxonomy'
      fullPath: '/taxonomy'
      preLoaderRoute: typeof ProtectedTaxonomyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/questions': {
      id: '/_protected/questions'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof ProtectedQuestionsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedUsersRoute
    }
    '/_protected/questions/': {
      id: '/_protected/questions/'
      path: '/'
      fullPath: '/questions/'
      preLoaderRoute: typeof ProtectedQuestionsIndexRouteImport
      parentRoute: typeof ProtectedQuestionsRoute
    }
    '/_protected/users/support': {
      id: '/_protected/users/support'
      path: '/support'
      fullPath: '/users/support'
      preLoaderRoute: typeof ProtectedUsersSupportRouteImport
      parentRoute: typeof ProtectedUsersRoute
    }
    '/_protected/users/subscriptions': {
      id: '/_protected/users/subscriptions'
      path: '/subscriptions'
      fullPath: '/users/subscriptions'
      preLoaderRoute: typeof ProtectedUsersSubscriptionsRouteImport
      parentRoute: typeof ProtectedUsersRoute
    }
    '/_protected/taxonomy/subjects': {
      id: '/_protected/taxonomy/subjects'
      path: '/subjects'
      fullPath: '/taxonomy/subjects'
      preLoaderRoute: typeof ProtectedTaxonomySubjectsRouteImport
      parentRoute: typeof ProtectedTaxonomyRoute
    }
    '/_protected/taxonomy/sub-chapters': {
      id: '/_protected/taxonomy/sub-chapters'
      path: '/sub-chapters'
      fullPath: '/taxonomy/sub-chapters'
      preLoaderRoute: typeof ProtectedTaxonomySubChaptersRouteImport
      parentRoute: typeof ProtectedTaxonomyRoute
    }
    '/_protected/taxonomy/grades': {
      id: '/_protected/taxonomy/grades'
      path: '/grades'
      fullPath: '/taxonomy/grades'
      preLoaderRoute: typeof ProtectedTaxonomyGradesRouteImport
      parentRoute: typeof ProtectedTaxonomyRoute
    }
    '/_protected/taxonomy/chapters': {
      id: '/_protected/taxonomy/chapters'
      path: '/chapters'
      fullPath: '/taxonomy/chapters'
      preLoaderRoute: typeof ProtectedTaxonomyChaptersRouteImport
      parentRoute: typeof ProtectedTaxonomyRoute
    }
    '/_protected/settings/security': {
      id: '/_protected/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof ProtectedSettingsSecurityRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/settings/profile': {
      id: '/_protected/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof ProtectedSettingsProfileRouteImport
      parentRoute: typeof ProtectedSettingsRoute
    }
    '/_protected/questions/new': {
      id: '/_protected/questions/new'
      path: '/new'
      fullPath: '/questions/new'
      preLoaderRoute: typeof ProtectedQuestionsNewRouteImport
      parentRoute: typeof ProtectedQuestionsRoute
    }
    '/_protected/questions/import': {
      id: '/_protected/questions/import'
      path: '/import'
      fullPath: '/questions/import'
      preLoaderRoute: typeof ProtectedQuestionsImportRouteImport
      parentRoute: typeof ProtectedQuestionsRoute
    }
    '/_protected/questions/blueprints': {
      id: '/_protected/questions/blueprints'
      path: '/blueprints'
      fullPath: '/questions/blueprints'
      preLoaderRoute: typeof ProtectedQuestionsBlueprintsRouteImport
      parentRoute: typeof ProtectedQuestionsRoute
    }
    '/_protected/questions/blueprints/': {
      id: '/_protected/questions/blueprints/'
      path: '/'
      fullPath: '/questions/blueprints/'
      preLoaderRoute: typeof ProtectedQuestionsBlueprintsIndexRouteImport
      parentRoute: typeof ProtectedQuestionsBlueprintsRoute
    }
    '/_protected/questions/$questionId/': {
      id: '/_protected/questions/$questionId/'
      path: '/$questionId'
      fullPath: '/questions/$questionId/'
      preLoaderRoute: typeof ProtectedQuestionsQuestionIdIndexRouteImport
      parentRoute: typeof ProtectedQuestionsRoute
    }
    '/_protected/questions/blueprints/new': {
      id: '/_protected/questions/blueprints/new'
      path: '/new'
      fullPath: '/questions/blueprints/new'
      preLoaderRoute: typeof ProtectedQuestionsBlueprintsNewRouteImport
      parentRoute: typeof ProtectedQuestionsBlueprintsRoute
    }
    '/_protected/questions/$questionId/edit': {
      id: '/_protected/questions/$questionId/edit'
      path: '/$questionId/edit'
      fullPath: '/questions/$questionId/edit'
      preLoaderRoute: typeof ProtectedQuestionsQuestionIdEditRouteImport
      parentRoute: typeof ProtectedQuestionsRoute
    }
    '/_protected/questions/blueprints/$blueprintId/edit': {
      id: '/_protected/questions/blueprints/$blueprintId/edit'
      path: '/$blueprintId/edit'
      fullPath: '/questions/blueprints/$blueprintId/edit'
      preLoaderRoute: typeof ProtectedQuestionsBlueprintsBlueprintIdEditRouteImport
      parentRoute: typeof ProtectedQuestionsBlueprintsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedQuestionsBlueprintsRouteChildren {
  ProtectedQuestionsBlueprintsNewRoute: typeof ProtectedQuestionsBlueprintsNewRoute
  ProtectedQuestionsBlueprintsIndexRoute: typeof ProtectedQuestionsBlueprintsIndexRoute
  ProtectedQuestionsBlueprintsBlueprintIdEditRoute: typeof ProtectedQuestionsBlueprintsBlueprintIdEditRoute
}

const ProtectedQuestionsBlueprintsRouteChildren: ProtectedQuestionsBlueprintsRouteChildren =
  {
    ProtectedQuestionsBlueprintsNewRoute: ProtectedQuestionsBlueprintsNewRoute,
    ProtectedQuestionsBlueprintsIndexRoute:
      ProtectedQuestionsBlueprintsIndexRoute,
    ProtectedQuestionsBlueprintsBlueprintIdEditRoute:
      ProtectedQuestionsBlueprintsBlueprintIdEditRoute,
  }

const ProtectedQuestionsBlueprintsRouteWithChildren =
  ProtectedQuestionsBlueprintsRoute._addFileChildren(
    ProtectedQuestionsBlueprintsRouteChildren,
  )

interface ProtectedQuestionsRouteChildren {
  ProtectedQuestionsBlueprintsRoute: typeof ProtectedQuestionsBlueprintsRouteWithChildren
  ProtectedQuestionsImportRoute: typeof ProtectedQuestionsImportRoute
  ProtectedQuestionsNewRoute: typeof ProtectedQuestionsNewRoute
  ProtectedQuestionsIndexRoute: typeof ProtectedQuestionsIndexRoute
  ProtectedQuestionsQuestionIdEditRoute: typeof ProtectedQuestionsQuestionIdEditRoute
  ProtectedQuestionsQuestionIdIndexRoute: typeof ProtectedQuestionsQuestionIdIndexRoute
}

const ProtectedQuestionsRouteChildren: ProtectedQuestionsRouteChildren = {
  ProtectedQuestionsBlueprintsRoute:
    ProtectedQuestionsBlueprintsRouteWithChildren,
  ProtectedQuestionsImportRoute: ProtectedQuestionsImportRoute,
  ProtectedQuestionsNewRoute: ProtectedQuestionsNewRoute,
  ProtectedQuestionsIndexRoute: ProtectedQuestionsIndexRoute,
  ProtectedQuestionsQuestionIdEditRoute: ProtectedQuestionsQuestionIdEditRoute,
  ProtectedQuestionsQuestionIdIndexRoute:
    ProtectedQuestionsQuestionIdIndexRoute,
}

const ProtectedQuestionsRouteWithChildren =
  ProtectedQuestionsRoute._addFileChildren(ProtectedQuestionsRouteChildren)

interface ProtectedSettingsRouteChildren {
  ProtectedSettingsProfileRoute: typeof ProtectedSettingsProfileRoute
  ProtectedSettingsSecurityRoute: typeof ProtectedSettingsSecurityRoute
}

const ProtectedSettingsRouteChildren: ProtectedSettingsRouteChildren = {
  ProtectedSettingsProfileRoute: ProtectedSettingsProfileRoute,
  ProtectedSettingsSecurityRoute: ProtectedSettingsSecurityRoute,
}

const ProtectedSettingsRouteWithChildren =
  ProtectedSettingsRoute._addFileChildren(ProtectedSettingsRouteChildren)

interface ProtectedTaxonomyRouteChildren {
  ProtectedTaxonomyChaptersRoute: typeof ProtectedTaxonomyChaptersRoute
  ProtectedTaxonomyGradesRoute: typeof ProtectedTaxonomyGradesRoute
  ProtectedTaxonomySubChaptersRoute: typeof ProtectedTaxonomySubChaptersRoute
  ProtectedTaxonomySubjectsRoute: typeof ProtectedTaxonomySubjectsRoute
}

const ProtectedTaxonomyRouteChildren: ProtectedTaxonomyRouteChildren = {
  ProtectedTaxonomyChaptersRoute: ProtectedTaxonomyChaptersRoute,
  ProtectedTaxonomyGradesRoute: ProtectedTaxonomyGradesRoute,
  ProtectedTaxonomySubChaptersRoute: ProtectedTaxonomySubChaptersRoute,
  ProtectedTaxonomySubjectsRoute: ProtectedTaxonomySubjectsRoute,
}

const ProtectedTaxonomyRouteWithChildren =
  ProtectedTaxonomyRoute._addFileChildren(ProtectedTaxonomyRouteChildren)

interface ProtectedUsersRouteChildren {
  ProtectedUsersSubscriptionsRoute: typeof ProtectedUsersSubscriptionsRoute
  ProtectedUsersSupportRoute: typeof ProtectedUsersSupportRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
}

const ProtectedUsersRouteChildren: ProtectedUsersRouteChildren = {
  ProtectedUsersSubscriptionsRoute: ProtectedUsersSubscriptionsRoute,
  ProtectedUsersSupportRoute: ProtectedUsersSupportRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
}

const ProtectedUsersRouteWithChildren = ProtectedUsersRoute._addFileChildren(
  ProtectedUsersRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedQuestionsRoute: typeof ProtectedQuestionsRouteWithChildren
  ProtectedSettingsRoute: typeof ProtectedSettingsRouteWithChildren
  ProtectedTaxonomyRoute: typeof ProtectedTaxonomyRouteWithChildren
  ProtectedUsersRoute: typeof ProtectedUsersRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedQuestionsRoute: ProtectedQuestionsRouteWithChildren,
  ProtectedSettingsRoute: ProtectedSettingsRouteWithChildren,
  ProtectedTaxonomyRoute: ProtectedTaxonomyRouteWithChildren,
  ProtectedUsersRoute: ProtectedUsersRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
